  #!/bin/sh

psql --host=172.18.0.3 --port=5432 --dbname=driver --username=driver <<EOF

insert into data_weatherdatalist (label, value, active) values ('Clear day','clear-day', False),
('Clear Night','clear-night', False),
('Cloudy','cloudy', False),
('Hail','hail', False),
('Partly Cloudy Day','partly-cloudy-day', False),
('Partly Cloudy Night','partly-cloudy-night', False),
('Rain','rain', False),
('Sleet','sleet', False),
('Snow','snow', False),
('Thunderstorm','thunderstorm', False),
('Tornado','tornado', False),
('Wind','wind', False),
('Thunderstorm with light rain','thunderstorm with light rain', False),
('Thunderstorm with rain','thunderstorm with rain', False),
('Thunderstorm with heavy rain','thunderstorm with heavy rain', False),
('Light thunderstorm','light thunderstorm', False),
('Thunderstorm','thunderstorm', False),
('Heavy thunderstorm','heavy thunderstorm', False),
('Ragged thunderstorm','ragged thunderstorm', False),
('Thunderstorm with light drizzle','thunderstorm with light drizzle', False),
('Thunderstorm with drizzle','thunderstorm with drizzle', False),
('Thunderstorm with heavy drizzle','thunderstorm with heavy drizzle', False),
('Light intensity drizzle','light intensity drizzle', False),
('Drizzle','drizzle', False),
('Heavy intensity drizzle','heavy intensity drizzle', False),
('Light intensity drizzle rain','light intensity drizzle rain', False),
('Drizzle rain','drizzle rain', False),
('Heavy intensity drizzle rain','heavy intensity drizzle rain', False),
('Shower rain and drizzle','shower rain and drizzle', False),
('Heavy shower rain and drizzle','heavy shower rain and drizzle', False),
('Shower drizzle','shower drizzle', False),
('Light rain','light rain', False),
('Moderate rain','moderate rain', False),
('Heavy intensity rain','heavy intensity rain', False),
('Very heavy rain','very heavy rain', False),
('Extreme rain','extreme rain', False),
('Freezing rain','freezing rain', False),
('Light intensity shower rain','light intensity shower rain', False),
('Shower rain','shower rain', False),
('Heavy intensity shower rain','heavy intensity shower rain', False),
('Ragged shower rain','ragged shower rain', False),
('Light snow','light snow', False),
('Heavy snow','Heavy snow', False),
('Light shower sleet','Light shower sleet', False),
('Shower sleet','Shower sleet', False),
('Light rain and snow','Light rain and snow', False),
('Rain and snow','Rain and snow', False),
('Light shower snow','Light shower snow', False),
('Shower snow','Shower snow', False),
('Heavy shower snow','Heavy shower snow', False),
('Mist','mist', False),
('Smoke','Smoke', False),
('Haze','Haze', False),
('Sand/ dust whirls','sand/ dust whirls', False),
('Fog','fog', False),
('Sand','sand', False),
('Dust','dust', False),
('Volcanic ash','volcanic ash', False),
('Squalls','squalls', False),
('Tornado','tornado', False),
('Clear sky','clear sky', False),
('Few clouds: 11-25%','few clouds: 11-25%', False),
('Scattered clouds: 25-50%','scattered clouds: 25-50%', False),
('Broken clouds: 51-84%','broken clouds: 51-84%', False),
('Overcast clouds: 85-100%','overcast clouds: 85-100%', False);
EOF
