# Generated by Django 5.1.5 on 2025-01-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_bulkuploaddetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverrecord',
            name='identity',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
