# Generated by Django 5.1.5 on 2025-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_driverrecord_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keydetail',
            name='GoogleLoginClientID',
        ),
        migrations.RemoveField(
            model_name='keydetail',
            name='mapillaryKey',
        ),
        migrations.AddField(
            model_name='keydetail',
            name='keyname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='keydetail',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
