# -*- coding: utf-8 -*-
from __future__ import absolute_import

from .base_model import BaseModel


class Data(BaseModel):

    attributes = [
        'land_use_passenger_side',
        'pedestrian_fencing',
        'intersection_quality',
        'grade',
        'number_of_lanes',
        'roadside_severity_driver_side_distance',
        'roadside_severity_passenger_side_object',
        'truck_speed_limit',
        'motorcycle_observed_flow',
        'land_use_driver_side',
        'roadside_severity_passenger_side_distance',
        'bicycle_star_rating_policy_target',
        'comments',
        'skid_resistance_grip',
        'motorcycle_percentage',
        'shoulder_rumble_strips',
        'operating_speed_mean',
        'dataset_id',
        'id',
        'paved_shoulder_passenger_side',
        'road_name',
        'paved_shoulder_driver_side',
        'intersecting_road_volume',
        'pedestrian_peak_hour_flow_along_the_road_passenger_side',
        'vehicle_occupant_star_rating_policy_target',
        'facilities_for_bicycles',
        'upgrade_cost',
        'bicycle_peak_hour_flow',
        'road_survey_date',
        'intersection_type',
        'roadworks',
        'centreline_rumble_strips',
        'pedestrian_observed_flow_along_the_road_driver_side',
        'area_type',
        'pedestrian_crossing_facilities_inspected_road',
        'school_zone_crossing_supervisor',
        'coder_name',
        'coding_date',
        'school_zone_warning',
        'latitude',
        'property_access_points',
        'motorcycle_speed_limit',
        'quality_of_curve',
        'image_reference',
        'sidewalk_driver_side',
        'roadside_severity_driver_side_object',
        'pedestrian_star_rating_policy_target',
        'pedestrian_crossing_quality',
        'facilities_for_motorised_two_wheelers',
        'pedestrian_crossing_facilities_intersecting_road',
        'pedestrian_peak_hour_flow_along_the_road_driver_side',
        'carriageway',
        'curvature',
        'differential_speed_limits',
        'roads_that_cars_can_read',
        'annual_fatality_growth_multiplier',
        'road_condition',
        'operating_speed_85th_percentile',
        'pedestrian_observed_flow_along_the_road_passenger_side',
        'distance',
        'median_type',
        'delineation',
        'date_modified',
        'speed_limit',
        'service_road',
        'pedestrian_peak_hour_flow_across_the_road',
        'sight_distance',
        'intersection_channelisation',
        'longitude',
        'vehicle_flow_aadt',
        'bicycle_observed_flow',
        'pedestrian_observed_flow_across_the_road',
        'length',
        'street_lighting',
        'motorcycle_star_rating_policy_target',
        'lane_width',
        'landmark',
        'date_created',
        'vehicle_parking',
        'sidewalk_passenger_side',
        'section',
        'speed_management_traffic_calming'
    ]
