# -*- coding: utf-8 -*-
from __future__ import absolute_import

from .base_model import BaseModel


class ModalInfo(BaseModel):

    attributes = [
        'dataset_id',
        'location_id',
        'latitude',
        'longitude',
        'bicycle_star_rating_star',
        'car_star_rating_star',
        'motorcycle_star_rating_star',
        'pedestrian_star_rating_star',
        'bicycle_fe',
        'car_fe',
        'motorcycle_fe',
        'pedestrian_fe',
        'countermeasures',
        'road_survey_date',
        'road_name',
        'section',
        'land_use_driver_side',
        'land_use_driver_side_text',
        'land_use_passenger_side',
        'land_use_passenger_side_text',
        'area_type',
        'area_type_text',
        'vehicle_parking',
        'vehicle_parking_text',
        'sight_distance',
        'sight_distance_text',
        'number_of_lanes',
        'number_of_lanes_text',
        'lane_width',
        'lane_width_text',
        'shoulder_rumble_strips',
        'shoulder_rumble_strips_text',
        'road_condition',
        'road_condition_text',
        'skid_resistance_grip',
        'skid_resistance_grip_text',
        'grade',
        'grade_text',
        'carriageway',
        'carriageway_text',
        'median_type',
        'median_type_text',
        'delineation',
        'delineation_text',
        'street_lighting',
        'street_lighting_text',
        'school_zone_warning',
        'school_zone_warning_text',
        'school_zone_crossing_supervisor',
        'school_zone_crossing_supervisor_text',
        'sidewalk_driver_side',
        'sidewalk_driver_side_text',
        'sidewalk_passenger_side',
        'sidewalk_passenger_side_text',
        'paved_shoulder_driver_side',
        'paved_shoulder_driver_side_text',
        'paved_shoulder_passenger_side',
        'paved_shoulder_passenger_side_text',
        'ped_fencing',
        'ped_fencing_text',
        'ped_crossing_facilities_inspected_road',
        'ped_crossing_facilities_inspected_road_text',
        'ped_crossing_facilities_intersecting_road',
        'ped_crossing_facilities_intersecting_road_text',
        'ped_crossing_quality',
        'ped_crossing_quality_text',
        'vehicle_flow',
        'vehicle_flow_text',
        'ped_peak_hour_flow_across',
        'ped_peak_hour_flow_across_text',
        'ped_peak_hour_flow_along_driver_side',
        'ped_peak_hour_flow_along_driver_side_text',
        'ped_peak_hour_flow_along_passenger_side',
        'ped_peak_hour_flow_along_passenger_side_text',
        'intersection_type',
        'intersection_type_text',
        'intersection_channelisation',
        'intersection_channelisation_text',
        'intersection_quality',
        'intersection_quality_text',
        'property_access_points',
        'property_access_points_text',
        'intersecting_road_volume',
        'intersecting_road_volume_text',
        'curvature',
        'curvature_text',
        'quality_of_curve',
        'quality_of_curve_text',
        'speed_limit',
        'speed_limit_text',
        'operating_speed_85th_percentile',
        'operating_speed_85th_percentile_text',
        'speed_management',
        'speed_management_text'
    ]

