# Generated by Django 5.1.5 on 2025-01-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='filter_json',
            field=models.JSONField(),
        ),
    ]
