# Generated by Django 5.1.5 on 2025-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='data_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundarypolygon',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='recordschema',
            name='schema',
            field=models.JSONField(),
        ),
    ]
