# Generated by Django 2.1 on 2021-01-06 06:09

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grout', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackSpot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('severity_score', models.FloatField()),
                ('num_records', models.PositiveIntegerField()),
                ('num_severe', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackSpotConfig',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('severity_percentile_threshold', models.FloatField(default=0.95, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackSpotRecordsFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('csv', models.FileField(upload_to='blackspot_records/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackSpotSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('effective_start', models.DateTimeField()),
                ('effective_end', models.DateTimeField(blank=True, null=True)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlackSpotTrainingCsv',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('csv', models.FileField(upload_to='training/blackspot/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadForecastTrainingCsv',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('csv', models.FileField(upload_to='training/forecast')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadSegmentsShapefile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shp_tgz', models.FileField(upload_to='road_segments/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blackspot',
            name='black_spot_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='black_spots.BlackSpotSet'),
        ),
    ]
