# Generated by Django 2.1 on 2021-01-06 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grout', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grout.Boundary')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grout.BoundaryPolygon')),
            ],
        ),
        migrations.CreateModel(
            name='CountryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_name', models.CharField(max_length=50)),
                ('archived', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupdetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('is_admin', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('csv_file', models.CharField(blank=True, max_length=100, null=True)),
                ('json_file', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('upload_for', models.CharField(blank=True, choices=[('user_panel', 'USER PANEL'), ('admin_panel', 'ADMIN PANEL')], max_length=15, null=True)),
                ('default_for_user_panel', models.BooleanField(default=False)),
                ('default_for_admin_panel', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grout.Boundary')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grout.BoundaryPolygon')),
            ],
        ),
        migrations.CreateModel(
            name='SendRoleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_group', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('city', models.ManyToManyField(blank=True, related_name='City', to='grout.BoundaryPolygon')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grout.Boundary')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('org', models.ManyToManyField(blank=True, to='driver_advanced_auth.Organization')),
                ('reg', models.ManyToManyField(blank=True, related_name='Region', to='grout.BoundaryPolygon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=254)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_staff', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('is_superuser', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('is_role_requested', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Not Requested', max_length=30)),
                ('geography', models.CharField(blank=True, max_length=20, null=True)),
                ('is_analyst', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('is_tech_analyst', models.BooleanField(choices=[(True, True), (False, False)], default=False)),
                ('google_user', models.BooleanField(default=False)),
                ('city', models.ManyToManyField(blank=True, related_name='User_City', to='grout.BoundaryPolygon')),
                ('groups', models.ManyToManyField(to='auth.Group')),
                ('org', models.ManyToManyField(blank=True, to='driver_advanced_auth.Organization')),
                ('reg', models.ManyToManyField(blank=True, related_name='User_Region', to='grout.BoundaryPolygon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
