# Generated by Django 3.0.8 on 2021-05-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_advanced_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='geography',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
